ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

CREATE OR REPLACE PROCEDURE CREATE_USERS AS
CURSOR CUR IS (
    SELECT MANV
    FROM QLDL.NHANSU
    WHERE MANV NOT IN (
        SELECT USERNAME FROM ALL_USERS
    )
);
USR CHAR(5);
STRSQL VARCHAR2(1000);
BEGIN
    OPEN CUR;
    LOOP
        FETCH CUR INTO USR;
        EXIT WHEN CUR%NOTFOUND;
        STRSQL := 'CREATE USER ' || USR || ' IDENTIFIED BY 123';
        EXECUTE IMMEDIATE(STRSQL);
        STRSQL := 'GRANT CREATE SESSION TO ' || USR;
        EXECUTE IMMEDIATE(STRSQL);
    END LOOP;
    CLOSE CUR;
END;
/

CREATE OR REPLACE PROCEDURE DROP_USERS AS
CURSOR CUR IS (
    SELECT MANV
    FROM QLDL.NHANSU
    WHERE MANV IN (
        SELECT USERNAME FROM ALL_USERS
    )
);
USR CHAR(5);
STRSQL VARCHAR2(1000);
BEGIN
    OPEN CUR;
    LOOP
        FETCH CUR INTO USR;
        EXIT WHEN CUR%NOTFOUND;
        STRSQL := 'DROP USER ' || USR || ' CASCADE';
        EXECUTE IMMEDIATE(STRSQL);
    END LOOP;
    CLOSE CUR;
END;
/
EXEC CREATE_USERS;
/
DROP PROCEDURE CREATE_USERS;
DROP PROCEDURE DROP_USERS;