ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

CREATE OR REPLACE PROCEDURE CREATE_USERS AS
CURSOR CUR IS (
    SELECT MANV
    FROM QLDL.NHANSU
    WHERE MANV NOT IN (
        SELECT USERNAME FROM ALL_USERS
    )
);
USR CHAR(5);
STRSQL VARCHAR2(1000);
BEGIN
    OPEN CUR;
    LOOP
        FETCH CUR INTO USR;
        EXIT WHEN CUR%NOTFOUND;
        STRSQL := 'CREATE USER ' || USR || ' IDENTIFIED BY 123';
        EXECUTE IMMEDIATE(STRSQL);
        STRSQL := 'GRANT CREATE SESSION TO ' || USR;
        EXECUTE IMMEDIATE(STRSQL);
    END LOOP;
    CLOSE CUR;
END;
/

CREATE OR REPLACE PROCEDURE DROP_USERS AS
CURSOR CUR IS (
    SELECT MANV
    FROM QLDL.NHANSU
    WHERE MANV IN (
        SELECT USERNAME FROM ALL_USERS
    )
);
USR CHAR(5);
STRSQL VARCHAR2(1000);
BEGIN
    OPEN CUR;
    LOOP
        FETCH CUR INTO USR;
        EXIT WHEN CUR%NOTFOUND;
        STRSQL := 'DROP USER ' || USR || ' CASCADE';
        EXECUTE IMMEDIATE(STRSQL);
    END LOOP;
    CLOSE CUR;
END;
/

CREATE OR REPLACE PROCEDURE ADD_ROLE (STRROLE VARCHAR2, VAITRO VARCHAR2) AS
CURSOR CUR IS (
    SELECT MANV
    FROM QLDL.NHANSU
    WHERE MANV IN (SELECT USERNAME FROM ALL_USERS) AND VAITRO = VAITRO
);
USR VARCHAR(5);
STRSQL VARCHAR2(1000);
BEGIN
    OPEN CUR;
    LOOP
        FETCH CUR INTO USR;
        EXIT WHEN CUR%NOTFOUND;
        STRSQL := 'GRANT ' || STRROLE || ' TO ' || USR;
        EXECUTE IMMEDIATE(STRSQL);
    END LOOP;
    CLOSE CUR;
END;
/

CREATE OR REPLACE PROCEDURE CREATE_STUDENTS AS
CURSOR CUR IS (
    SELECT MASV
    FROM QLDL.SINHVIEN
    WHERE MASV NOT IN (SELECT USERNAME FROM ALL_USERS)
);
USR CHAR(5);
STRSQL VARCHAR2(1000);
BEGIN
    OPEN CUR;
    LOOP
        FETCH CUR INTO USR;
        EXIT WHEN CUR%NOTFOUND;
        STRSQL := 'CREATE USER ' || USR || ' IDENTIFIED BY 123';
        EXECUTE IMMEDIATE(STRSQL);
        STRSQL := 'GRANT CREATE SESSION TO ' || USR;
        EXECUTE IMMEDIATE(STRSQL);
        STRSQL := 'GRANT SV TO ' || USR;
        EXECUTE IMMEDIATE(STRSQL);
    END LOOP;
    CLOSE CUR;
END;
/

CREATE OR REPLACE PROCEDURE DROP_STUDENTS AS
CURSOR CUR IS (
    SELECT MASV
    FROM QLDL.SINHVIEN
    WHERE MASV IN (SELECT USERNAME FROM ALL_USERS)
);
USR CHAR(5);
STRSQL VARCHAR2(1000);
BEGIN
    OPEN CUR;
    LOOP
        FETCH CUR INTO USR;
        EXIT WHEN CUR%NOTFOUND;
        STRSQL := 'DROP USER ' || USR || ' CASCADE';
        EXECUTE IMMEDIATE(STRSQL);
    END LOOP;
    CLOSE CUR;
END;
/



CREATE ROLE NVCB;
CREATE ROLE GV;
CREATE ROLE GIAOVU;
CREATE ROLE TRGDV;
CREATE ROLE TRGKHOA;
CREATE ROLE SV;
EXEC CREATE_USERS;
EXEC CREATE_STUDENTS;

EXEC ADD_ROLE('NVCB', 'Nhan vien co ban');
EXEC ADD_ROLE('GV', 'Giang vien');
EXEC ADD_ROLE('GIAOVU', 'Giao vu');
EXEC ADD_ROLE('TRGDV', 'Truong don vi');
EXEC ADD_ROLE('TRGKHOA', 'Truong khoa');

/

EXEC DROP_USERS;
EXEC DROP_STUDENT;

DROP PROCEDURE CREATE_USERS;
DROP PROCEDURE DROP_USERS;
DROP PROCEDURE ADD_ROLE;
DROP PROCEDURE CREATE_STUDENTS;
DROP PROCEDURE DROP_STUDENTS;

DROP ROLE NVCB;
DROP ROLE GV;
DROP ROLE GIAOVU;
DROP ROLE TRGDV;
DROP ROLE TRGKHOA;
DROP ROLE SV;


