SELECT * FROM QLDL.NHANSU;
SELECT * FROM QLDL.SINHVIEN;
SELECT * FROM QLDL.DONVI;
SELECT * FROM QLDL.HOCPHAN;
SELECT * FROM QLDL.KHMO;

SELECT * FROM QLDL.PHANCONG;

SELECT * FROM QLDL.DANGKY;

-- CHINH SUA TREN CAC DONG LIEN QUAN DEN HP DO VAN PHONG KHOA PHU TRACH
UPDATE QLDL.PHANCONG
SET MAGV = 'NV002'
WHERE MAHP = 'HP001';

