-- TRUONG DON VI

SELECT * FROM QLDL.NHANSU;
SELECT * FROM QLDL.SINHVIEN;
SELECT * FROM QLDL.DONVI;
SELECT * FROM QLDL.HOCPHAN;
SELECT * FROM QLDL.KHMO;

SELECT * FROM QLDL.PHANCONG;

SELECT * FROM QLDL.DANGKY;

UPDATE QLDL.PHANCONG
SET MAGV = 'NV003'
WHERE MAHP = 'HP001';