--TRUONG KHOA

SELECT * FROM QLDL.NHANSU;
SELECT * FROM QLDL.SINHVIEN;
SELECT * FROM QLDL.DONVI;
SELECT * FROM QLDL.HOCPHAN;
SELECT * FROM QLDL.KHMO;

SELECT * FROM QLDL.PHANCONG;

SELECT * FROM QLDL.DANGKY;

INSERT INTO QLDL.PHANCONG VALUES ('NV001', 'HP001', 'HK1', 2023, 'CT001');
--INSERT INTO QLDL.PHANCONG VALUES ('NV001', 'HP002', 'HK1', 2023, 'CT001');

UPDATE QLDL.PHANCONG
SET MAGV = 'NV003'
WHERE MAHP = 'HP001' AND MAGV = 'NV001';

DELETE QLDL.PHANCONG
WHERE MAHP = 'HP001' AND MAGV = 'NV003';

--DELETE QLDL.PHANCONG
--WHERE MAHP = 'HP002' AND MAGV = 'NV002';