-- B1: 
-- KIEM TRA BAT OLS
SELECT VALUE FROM v$option WHERE parameter = 'Oracle Label Security'; 
SELECT status FROM dba_ols_status WHERE name = 'OLS_CONFIGURE_STATUS'; 

-- DANG KY NEU CHUA BAT
Begin
LBACSYS.CONFIGURE_OLS;
LBACSYS.OLS_ENFORCEMENT.ENABLE_OLS;
end;
/ -- KHOI DONG LAI

-- KIEM TRA PDB
select * from v$services; 

ALTER USER lbacsys IDENTIFIED BY lbacsys ACCOUNT UNLOCK; 

ALTER PLUGGABLE DATABASE mypdb OPEN READ WRITE; 

ALTER SESSION SET CONTAINER= mypdb; 
SHOW CON_NAME; 

-- B2: TAO USER CHUA DB, CAP QUYEN
CREATE USER QLDL_OLS IDENTIFIED BY 123 CONTAINER = CURRENT; 
GRANT CONNECT,RESOURCE TO QLDL_OLS; --CAP QUYEN CONNECT VÀ RESOURCE 
GRANT UNLIMITED TABLESPACE TO QLDL_OLS; --CAP QUOTA
GRANT SELECT ANY DICTIONARY TO QLDL_OLS; --CAP QUYEN DOC DICTIONARY 

GRANT EXECUTE ON LBACSYS.CONFIGURE_OLS TO QLDL_OLS;
GRANT EXECUTE ON LBACSYS.OLS_ENFORCEMENT TO QLDL_OLS;

-- CAP QUYEN EXECUTE CHO QLDL_OLS
GRANT EXECUTE ON LBACSYS.SA_COMPONENTS TO QLDL_OLS WITH GRANT OPTION; 
GRANT EXECUTE ON LBACSYS.sa_user_admin TO QLDL_OLS WITH GRANT OPTION; 
GRANT EXECUTE ON LBACSYS.sa_label_admin TO QLDL_OLS WITH GRANT OPTION; 
GRANT EXECUTE ON sa_policy_admin TO QLDL_OLS WITH GRANT OPTION; 
GRANT EXECUTE ON char_to_label TO QLDL_OLS WITH GRANT OPTION;
GRANT REGION_POLICY_DBA TO QLDL_OLS;

-- ADD QLDL_OLS VÀO LBAC_DBA 
GRANT LBAC_DBA TO QLDL_OLS; 
GRANT EXECUTE ON sa_sysdba TO QLDL_OLS;  
GRANT EXECUTE ON TO_LBAC_DATA_LABEL TO QLDL_OLS; -- CAP QUYEN THUC THI


-- B4: KIEM TRA CAC LABEL DA TAO
SELECT * FROM DBA_SA_LEVELS; 
SELECT * FROM DBA_SA_COMPARTMENTS;
SELECT * FROM DBA_SA_GROUPS; 
SELECT * FROM DBA_SA_GROUP_HIERARCHY; 

-- B9: TAO USER 
DROP USER USRTGKH;
DROP USER USRTDVCS1;
DROP USER USRTDVCS2;
DROP USER USRGV;
DROP USER USRGIAOVU;
DROP USER USRNV;
DROP USER USRSV;
DROP USER USRTDVCS1KHMT;
DROP USER USRTDVCS2KHMT;

CREATE USER USRTGKH IDENTIFIED BY 123;
CREATE USER USRTDVCS1 IDENTIFIED BY 123;
CREATE USER USRTDVCS2 IDENTIFIED BY 123;
CREATE USER USRGV IDENTIFIED BY 123;
CREATE USER USRGIAOVU IDENTIFIED BY 123;
CREATE USER USRNV IDENTIFIED BY 123;
CREATE USER USRSV IDENTIFIED BY 123;

CREATE USER USRTDVCS1KHMT IDENTIFIED BY 123;
CREATE USER USRTDVCS2KHMT IDENTIFIED BY 123;

GRANT TRGKHOA TO USRTGKH;
GRANT TRGDV TO USRTDVCS1;
GRANT TRGDV TO USRTDVCS2;
GRANT GV TO USRGV;
GRANT GIAOVU TO USRGIAOVU;
GRANT NVCB TO USRNV;
GRANT SV TO USRSV;

GRANT CREATE SESSION TO USRTGKH;
GRANT CREATE SESSION TO USRTDVCS1;
GRANT CREATE SESSION TO USRTDVCS2;
GRANT CREATE SESSION TO USRGV;
GRANT CREATE SESSION TO USRGIAOVU;
GRANT CREATE SESSION TO USRNV;
GRANT CREATE SESSION TO USRSV;

GRANT CREATE SESSION TO USRTDVCS1KHMT;
GRANT CREATE SESSION TO USRTDVCS2KHMT;

GRANT SELECT ON QLDL_OLS.THONGBAO TO USRTGKH;
GRANT SELECT ON QLDL_OLS.THONGBAO TO USRTDVCS1;
GRANT SELECT ON QLDL_OLS.THONGBAO TO USRTDVCS2;
GRANT SELECT ON QLDL_OLS.THONGBAO TO USRGV;
GRANT SELECT ON QLDL_OLS.THONGBAO TO USRGIAOVU;
GRANT SELECT ON QLDL_OLS.THONGBAO TO USRNV;
GRANT SELECT ON QLDL_OLS.THONGBAO TO USRSV;

GRANT SELECT ON QLDL_OLS.THONGBAO TO USRTDVCS1KHMT;
GRANT SELECT ON QLDL_OLS.THONGBAO TO USRTDVCS2KHMT;

-- B11: KIEM TRA LABEL USER
SELECT * FROM ALL_SA_USER_LABELS;