--1) KICH HOAT AUDIT
ALTER SYSTEM SET audit_trail=db SCOPE=SPFILE;

--2)
-- THEO DOI HANH VI CUA USER CU THE (USER: SV001)
AUDIT ALL BY SV001 BY ACCESS;
-- THEO DOI CAC LENH INSERT, UPDATE, DELETE TREN BANG PHANCONG
AUDIT INSERT, UPDATE, DELETE ON QLDL.PHANCONG;
-- THEO DOI INSERT TREN BANG NHANSU KHONG THANH CONG
AUDIT INSERT ON QLDL.NHANSU WHENEVER NOT SUCCESSFUL; 



--3)
--a) GHI LAI HANH VI CAP NHAT DANGKY TAI CAC TRUONG LIEN QUAN DEN DIEM SO 
--CUA NHUNG NGUOI KHONG PHAI GIAO VIEN


--b) GHI LAI HANH VI DOC TREN TRUONG PHU CAP CUA NGUOI KHAC O QUAN HE NHANSU



--4)
SELECT VIEW_NAME FROM DBA_VIEWS WHERE VIEW_NAME LIKE 'DBA%AUDIT%' ORDER BY VIEW_NAME;

SELECT * FROM DBA_AUDIT_TRAIL WHERE OWNER = 'QLDL' ORDER BY TIMESTAMP;
